-- MySQL Script generated by MySQL Workbench
-- 12/12/16 02:47:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema msc_bd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `msc_bd` ;

-- -----------------------------------------------------
-- Schema msc_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `msc_bd` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `msc_bd` ;

-- -----------------------------------------------------
-- Table `msc_bd`.`ligue_para_mim`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `msc_bd`.`ligue_para_mim` ;

CREATE TABLE IF NOT EXISTS `msc_bd`.`ligue_para_mim` (
  `id_ligue_para_mim` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NULL,
  `telefone` VARCHAR(250) NULL,
  `email` VARCHAR(250) NULL,
  `status` ENUM('PENDENTE', 'RETORNADO') NULL,
  `data` VARCHAR(20) NULL,
  PRIMARY KEY (`id_ligue_para_mim`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `msc_bd`.`contatos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `msc_bd`.`contatos` ;

CREATE TABLE IF NOT EXISTS `msc_bd`.`contatos` (
  `id_contato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NULL,
  `empresa` VARCHAR(250) NULL,
  `email` VARCHAR(250) NULL,
  `msg` LONGTEXT NULL,
  `data` VARCHAR(45) NULL,
  PRIMARY KEY (`id_contato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `msc_bd`.`pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `msc_bd`.`pedidos` ;

CREATE TABLE IF NOT EXISTS `msc_bd`.`pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `solicitante` VARCHAR(250) NULL,
  `empresa` VARCHAR(250) NULL,
  `descricao_empresa` LONGTEXT NULL,
  `outras_info_empresa` LONGTEXT NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(250) NULL,
  `cidade` VARCHAR(250) NULL,
  `uf` VARCHAR(45) NULL,
  `descricao_projeto` LONGTEXT NULL,
  `info_complementares` VARCHAR(250) NULL,
  `solucoes` VARCHAR(45) NULL,
  `data_pedido` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `msc_bd`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `msc_bd`.`clientes` ;

CREATE TABLE IF NOT EXISTS `msc_bd`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_razao` VARCHAR(250) NULL,
  `email` VARCHAR(250) NULL,
  `tel_1` VARCHAR(45) NULL,
  `tel_2` VARCHAR(45) NULL,
  `cpf_cnpj` VARCHAR(45) NULL,
  `nome_contato` VARCHAR(250) NULL,
  `descricao_empresa` LONGTEXT NULL,
  `outras_info_empresa` LONGTEXT NULL,
  `cidade` VARCHAR(150) NULL,
  `uf` VARCHAR(45) NULL,
  `logradouro` VARCHAR(150) NULL,
  `num_residencia` VARCHAR(45) NULL,
  `cep` VARCHAR(15) NULL,
  `obs` VARCHAR(250) NULL,
  `password` VARCHAR(250) NULL,
  `tipo` VARCHAR(45) NULL,
  `rg_ie` VARCHAR(200) NULL,
  `nome_usuario` VARCHAR(200) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `msc_bd`.`solicitacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `msc_bd`.`solicitacoes` ;

CREATE TABLE IF NOT EXISTS `msc_bd`.`solicitacoes` (
  `id_solicitacao` INT NOT NULL AUTO_INCREMENT,
  `data_solicitacao` VARCHAR(45) NULL,
  `status` ENUM('ABERTO', 'EM DEV', 'FECHADO') NULL,
  `fk_cliente` INT NULL,
  `codigo` VARCHAR(250) NULL,
  `solucao` ENUM('WEBDEV', 'SISTEMAS', 'INFRA', 'TREINA') NULL,
  `ciclo_pagamento` ENUM('INTEGRAL','2 PARCELAS','MENSAL','TRIMESTRAL','SEMESTRAL','ANUAL') NULL,
  `detalhes` VARCHAR(200) NULL,
  PRIMARY KEY (`id_solicitacao`),
  INDEX `fk_id_cliente_idx` (`fk_cliente` ASC),
  INDEX `fk_id_cliente` (`fk_cliente` ASC),
  CONSTRAINT `fk_cliente_solicitacao`
    FOREIGN KEY (`fk_cliente`)
    REFERENCES `msc_bd`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `msc_bd`.`chamados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `msc_bd`.`chamados` ;

CREATE TABLE IF NOT EXISTS `msc_bd`.`chamados` (
  `id_chamado` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` LONGTEXT NULL,
  `data_cadastro` VARCHAR(20) NULL,
  `assunto` VARCHAR(200) NULL,
  `status` ENUM('PENDENTE','EM ATENDIMENTO','TERMINADO') NULL,
  `solucao` LONGTEXT NULL,
  `obs` LONGTEXT NULL,
  `fk_cliente` INT(11) NULL,
  `nome_doc_anexo` VARCHAR(250) NULL,
  PRIMARY KEY (`id_chamado`),
  INDEX `fk_cliente_idx` (`fk_cliente` ASC),
  CONSTRAINT `fk_cliente_chamado`
    FOREIGN KEY (`fk_cliente`)
    REFERENCES `msc_bd`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `msc_bd`.`assentamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `msc_bd`.`assentamentos` ;

CREATE TABLE IF NOT EXISTS `msc_bd`.`assentamentos` (
  `id_assentamento` INT(11) NOT NULL AUTO_INCREMENT,
  `assentamento` LONGTEXT NULL,
  `data_cadastro` VARCHAR(20) NULL,
  `autor` ENUM('CLIENTE','OPERADOR') NULL,
  `fk_chamado` INT(11) NULL,
  PRIMARY KEY (`id_assentamento`),
  INDEX `fk_chamado_idx` (`fk_chamado` ASC),
  CONSTRAINT `fk_chamado_assentamento`
    FOREIGN KEY (`fk_chamado`)
    REFERENCES `msc_bd`.`chamados` (`id_chamado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `msc_bd`.`solucoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `msc_bd`.`solucoes` ;

CREATE TABLE IF NOT EXISTS `msc_bd`.`solucoes` (
  `id_solucao` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NULL,
  `descricao` VARCHAR(250) NULL,
  `codigo` VARCHAR(20) NULL,
  `status` ENUM('ATIVO', 'INATIVO') NULL,
  PRIMARY KEY (`id_solucao`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `msc_bd`.`pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `msc_bd`.`pagamentos` ;

CREATE TABLE IF NOT EXISTS `msc_bd`.`pagamentos` (
  `id_pagamento` INT(11) NOT NULL AUTO_INCREMENT,
  `mes` INT(11) NULL,
  `ano` INT(11) NULL,
  `tipo` ENUM('LICENCA','PARCELA','MENSALIDADE','INTEGRAL') NULL,
  `num_licencas` INT(11) NULL,
  `valor` VARCHAR(45) NULL,
  `status` ENUM('ABERTO','FECHADO') NULL,
  `fk_solicitacao` INT(11) NULL,
  `codigo` VARCHAR(250) NULL,
  `fk_solucao` INT(11) NULL,
  `num_de_dias` INT(11) NULL,
  `status_pagamento` ENUM('AGUARDANDO','CONFIRMADO') NULL DEFAULT NULL,
  `a_partir_de` DATE NULL,
  PRIMARY KEY (`id_pagamento`),
  INDEX `fk_solicitacao_idx` (`fk_solicitacao` ASC),
  INDEX `fk_solucao_idx` (`fk_solucao` ASC),
  CONSTRAINT `fk_solicitacao_pag`
    FOREIGN KEY (`fk_solicitacao`)
    REFERENCES `msc_bd`.`solicitacoes` (`id_solicitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solucao_pag`
    FOREIGN KEY (`fk_solucao`)
    REFERENCES `msc_bd`.`solucoes` (`id_solucao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `msc_bd`.`sistemas_ativados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `msc_bd`.`sistemas_ativados` ;

CREATE TABLE IF NOT EXISTS `msc_bd`.`sistemas_ativados` (
  `id_sis_ativo` INT(11) NOT NULL AUTO_INCREMENT,
  `id_soft` VARCHAR(45) NULL,
  `data` VARCHAR(45) NULL,
  `chave` LONGTEXT NULL,
  `fk_pagamento` INT NULL,
  PRIMARY KEY (`id_sis_ativo`),
  INDEX `fk_pagamento_idx` (`fk_pagamento` ASC),
  CONSTRAINT `fk_pagamento_ativo`
    FOREIGN KEY (`fk_pagamento`)
    REFERENCES `msc_bd`.`pagamentos` (`id_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `msc_bd`.`versoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `msc_bd`.`versoes` ;

CREATE TABLE IF NOT EXISTS `msc_bd`.`versoes` (
  `id_versao` INT NOT NULL AUTO_INCREMENT,
  `fk_sistema` INT NULL,
  `compilacao` VARCHAR(45) NULL,
  `data_cadastro` DATE NULL,
  `nome_arquivo` VARCHAR(45) NULL,
  `versao` VARCHAR(45) NULL,
  `tamanho_em_bytes` VARCHAR(45) NULL,
  PRIMARY KEY (`id_versao`),
  INDEX `fk_sistema_idx` (`fk_sistema` ASC),
  CONSTRAINT `fk_sistema_versao`
    FOREIGN KEY (`fk_sistema`)
    REFERENCES `msc_bd`.`solucoes` (`id_solucao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
